name: Build and publish containers imnages

"on":
  push:
    tags:
      - '*'
    branches:
      - 'master'

jobs:
  webapp:
    uses: ./.github/actions/push_to_registry
    with:
      DIRECTORY: "webapp"
