name: Build and publish containers imnages

"on":
  push:
    tags:
      - '*'
    branches:
      - 'master'

jobs:
  build-and-push-image-webapp:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Push webapp to registry
        uses: ./.github/actions/push_to_registry
        with:
          DIRECTORY: "webapp"  
